sudo: required
language: generic
services:
    - docker
before_install:
    - docker build -t codeblox/react-test ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true codeblox/react-test npm test -- --coverage
after_success:
    - docker build -t codeblox/multi-client ./client
    - docker build -t codeblox/multi-nginx ./nginx
    - docker build -t codeblox/multi-server ./server
    - docker build -t codeblox/multi-worker ./worker
    # Log into docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push to Docker Hub
    - docker push codeblox/multi-client
    - docker push codeblox/multi-nginx
    - docker push codeblox/multi-server
    - docker push codeblox/multi-worker